FROM node:22-alpine AS deps
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG RUNTIME_MODE
ARG SITE_URL
ARG LOCAL_ONLY_MODE
ARG ALLOW_ADMIN_OUTSIDE_LOCAL_MODE
ARG ENABLE_ADMIN_SUBMISSIONS_REVIEW
ARG REVIEW_SURFACES_VISIBLE
ARG REVIEW_ACCESS_KEY
ARG REVIEW_ACCESS_COOKIE_NAME
ARG DEPLOYMENT_STAMP_VISIBLE
ARG DEPLOY_COMMIT_SHA
ARG DEPLOY_REF
ARG DEPLOY_BUILD_TIME_UTC
ARG SEO_ALLOW_INDEXING
ARG REQUEST_LAYOUT_CONTRACT_VERSION
ENV RUNTIME_MODE=$RUNTIME_MODE
ENV SITE_URL=$SITE_URL
ENV LOCAL_ONLY_MODE=$LOCAL_ONLY_MODE
ENV ALLOW_ADMIN_OUTSIDE_LOCAL_MODE=$ALLOW_ADMIN_OUTSIDE_LOCAL_MODE
ENV ENABLE_ADMIN_SUBMISSIONS_REVIEW=$ENABLE_ADMIN_SUBMISSIONS_REVIEW
ENV REVIEW_SURFACES_VISIBLE=$REVIEW_SURFACES_VISIBLE
ENV REVIEW_ACCESS_KEY=$REVIEW_ACCESS_KEY
ENV REVIEW_ACCESS_COOKIE_NAME=$REVIEW_ACCESS_COOKIE_NAME
ENV DEPLOYMENT_STAMP_VISIBLE=$DEPLOYMENT_STAMP_VISIBLE
ENV DEPLOY_COMMIT_SHA=$DEPLOY_COMMIT_SHA
ENV DEPLOY_REF=$DEPLOY_REF
ENV DEPLOY_BUILD_TIME_UTC=$DEPLOY_BUILD_TIME_UTC
ENV SEO_ALLOW_INDEXING=$SEO_ALLOW_INDEXING
ENV REQUEST_LAYOUT_CONTRACT_VERSION=$REQUEST_LAYOUT_CONTRACT_VERSION
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
RUN npm prune --omit=dev

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ARG RUNTIME_MODE
ARG SITE_URL
ARG LOCAL_ONLY_MODE
ARG ALLOW_ADMIN_OUTSIDE_LOCAL_MODE
ARG ENABLE_ADMIN_SUBMISSIONS_REVIEW
ARG REVIEW_SURFACES_VISIBLE
ARG REVIEW_ACCESS_KEY
ARG REVIEW_ACCESS_COOKIE_NAME
ARG DEPLOYMENT_STAMP_VISIBLE
ARG DEPLOY_COMMIT_SHA
ARG DEPLOY_REF
ARG DEPLOY_BUILD_TIME_UTC
ARG SEO_ALLOW_INDEXING
ARG REQUEST_LAYOUT_CONTRACT_VERSION
ENV RUNTIME_MODE=$RUNTIME_MODE
ENV SITE_URL=$SITE_URL
ENV LOCAL_ONLY_MODE=$LOCAL_ONLY_MODE
ENV ALLOW_ADMIN_OUTSIDE_LOCAL_MODE=$ALLOW_ADMIN_OUTSIDE_LOCAL_MODE
ENV ENABLE_ADMIN_SUBMISSIONS_REVIEW=$ENABLE_ADMIN_SUBMISSIONS_REVIEW
ENV REVIEW_SURFACES_VISIBLE=$REVIEW_SURFACES_VISIBLE
ENV REVIEW_ACCESS_KEY=$REVIEW_ACCESS_KEY
ENV REVIEW_ACCESS_COOKIE_NAME=$REVIEW_ACCESS_COOKIE_NAME
ENV DEPLOYMENT_STAMP_VISIBLE=$DEPLOYMENT_STAMP_VISIBLE
ENV DEPLOY_COMMIT_SHA=$DEPLOY_COMMIT_SHA
ENV DEPLOY_REF=$DEPLOY_REF
ENV DEPLOY_BUILD_TIME_UTC=$DEPLOY_BUILD_TIME_UTC
ENV SEO_ALLOW_INDEXING=$SEO_ALLOW_INDEXING
ENV REQUEST_LAYOUT_CONTRACT_VERSION=$REQUEST_LAYOUT_CONTRACT_VERSION
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 4850
HEALTHCHECK --interval=20s --timeout=5s --start-period=25s --retries=6 \
  CMD node -e "require('http').get('http://localhost:4850',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))"
CMD ["npm", "run", "start"]
