import type { SubmissionType } from "./types";

export const formDefaults: Record<SubmissionType, Record<string, string>> = {
  general: {
    type: "general",
    fullName: "",
    phone: "",
    email: "",
    address: "",
    preferredDate: "",
    urgency: "normal",
    message: "",
    topic: "",
  },
  "septic-service": {
    type: "septic-service",
    fullName: "",
    phone: "",
    email: "",
    address: "",
    preferredDate: "",
    urgency: "normal",
    message: "",
    tankSizeGallons: "",
    tankCount: "",
    lidsExposed: "",
    backupSigns: "",
  },
  evaluation: {
    type: "evaluation",
    fullName: "",
    phone: "",
    email: "",
    address: "",
    preferredDate: "",
    urgency: "normal",
    message: "",
    roleInSale: "",
    brokerageOrCompany: "",
    closingDate: "",
    occupancyStatus: "",
  },
  rental: {
    type: "rental",
    fullName: "",
    phone: "",
    email: "",
    address: "",
    preferredDate: "",
    urgency: "normal",
    message: "",
    eventType: "",
    unitCount: "",
    rentalDuration: "",
    serviceFrequency: "",
    siteType: "",
  },
  "commercial-service": {
    type: "commercial-service",
    fullName: "",
    phone: "",
    email: "",
    address: "",
    preferredDate: "",
    urgency: "normal",
    message: "",
    facilityName: "",
    facilityType: "",
    serviceNeeded: "",
    greaseTrapCount: "",
    onSiteContact: "",
  },
};
