import type { SubmissionType } from "./types";

export const fieldPurposeMap: Record<SubmissionType, Record<string, string>> = {
  general: {
    type: "Routes payload into the general lane workflow.",
    fullName: "Provides a named contact for callback and scheduling ownership.",
    phone: "Primary callback path for urgent triage and dispatch follow-up.",
    email: "Backup written follow-up channel for non-urgent coordination.",
    preferredDate: "Captures requested timing so routing can prioritize windows.",
    preferredTime: "Captures preferred callback or arrival time window.",
    urgency: "Flags urgency tier for queue ordering.",
    message: "Required freeform context for nuanced requests.",
    streetAddress: "Location detail for on-site work when relevant.",
    city: "City-level routing and service-area check.",
    zip: "Service-area confirmation and route planning.",
    state: "State normalization for address completeness.",
    address: "Legacy address compatibility field retained for payload normalization.",
    topic: "Classifies the request category before review.",
    serviceLocationInvolved: "Determines whether location fields must be considered for dispatch.",
  },
  "septic-service": {
    type: "Routes payload into the septic-service lane.",
    fullName: "Identifies requester responsible for on-site coordination.",
    phone: "Primary dispatch callback path.",
    email: "Secondary follow-up channel for schedule confirmations.",
    preferredDate: "Captures requested service window.",
    preferredTime: "Captures preferred callback or arrival time window.",
    urgency: "Emergency triage and queue priority.",
    message: "Required narrative details for unusual symptoms or constraints.",
    streetAddress: "Required service destination.",
    city: "Required city routing detail.",
    zip: "Required service-area and route planning detail.",
    state: "Address normalization field.",
    address: "Legacy compatibility address field.",
    tankSizeGallons: "Determines equipment and pumping assumptions.",
    tankCount: "Impacts scope and dispatch prep.",
    lidsExposed: "Indicates potential access/prep requirements.",
    tankLocationKnown: "Signals whether locate assistance may be needed.",
    problemSigns: "Structured symptom capture for dispatch triage.",
    additionalWarningDetails: "Optional symptom timing/location clarifier.",
    accessIssues: "Structured access blockers for arrival planning.",
    existingCustomer: "Helps staff retrieve account/service history.",
    propertyUsage: "Classifies residential vs commercial routing context.",
    systemPumpedBefore: "Assists with service-history assumptions.",
  },
  evaluation: {
    type: "Routes payload into the home-sale evaluation lane.",
    fullName: "Primary coordinator identity for transaction communication.",
    phone: "Direct callback channel for timeline-sensitive updates.",
    email: "Written coordination trail for multi-party workflows.",
    preferredDate: "Requested scheduling window for evaluation planning.",
    preferredTime: "Captures preferred callback or arrival time window.",
    urgency: "Prioritizes closing-deadline pressure.",
    message: "Required freeform notes for transaction-specific constraints.",
    streetAddress: "Evaluation property location.",
    city: "City-level route planning.",
    zip: "Service-area and travel planning.",
    state: "Address normalization field.",
    address: "Legacy compatibility address field.",
    roleInSale: "Identifies buyer/seller/realtor perspective.",
    brokerageOrCompany: "Adds business context for transaction stakeholders.",
    closingDate: "Key deadline signal for prioritization.",
    occupancyStatus: "Determines access assumptions.",
    accessInstructions: "Captures lockbox/gate/access constraints.",
    utilityOnStatus: "Confirms evaluation readiness conditions.",
    occupantPresent: "Sets arrival coordination expectations.",
    propertyType: "Property context for scheduling/resource planning.",
  },
  rental: {
    type: "Routes payload into the portable rental lane.",
    fullName: "Request owner for delivery/service follow-up.",
    phone: "Primary scheduling and delivery callback path.",
    email: "Backup channel for quote and confirmation details.",
    preferredDate: "Requested delivery/start date.",
    preferredTime: "Captures preferred callback or arrival time window.",
    urgency: "Queue priority for near-term events/projects.",
    message: "Required freeform notes for site-specific needs.",
    streetAddress: "Delivery/service location.",
    city: "City routing for logistics.",
    zip: "Service-area and route planning.",
    state: "Address normalization field.",
    address: "Legacy compatibility address field.",
    eventType: "Classifies use case for unit planning.",
    unitCount: "Core quantity input for quote and dispatch.",
    rentalDuration: "Defines service period and cadence assumptions.",
    serviceFrequency: "Determines maintenance schedule.",
    siteType: "Indicates access complexity.",
    handwashStationNeeded: "Captures required add-on units.",
    adaUnitNeeded: "Captures accessibility unit requirements.",
    placementSurface: "Placement planning for safe setup.",
    siteAccessNotes: "Optional logistics constraints and notes.",
  },
  "commercial-service": {
    type: "Routes payload into the commercial-service lane.",
    fullName: "Requester identity for operational coordination.",
    phone: "Primary callback for urgent facility issues.",
    email: "Written channel for confirmations and follow-up.",
    preferredDate: "Requested service window.",
    preferredTime: "Captures preferred callback or arrival time window.",
    urgency: "Queue priority for operational risk.",
    message: "Required freeform context for non-standard constraints.",
    streetAddress: "Facility service location.",
    city: "City routing for dispatch.",
    zip: "Service-area and route planning.",
    state: "Address normalization field.",
    address: "Legacy compatibility address field.",
    facilityName: "Identifies serviced business/facility.",
    facilityType: "Classifies operational context.",
    serviceNeeded: "Defines requested commercial service type.",
    greaseTrapCount: "Scope estimate for labor/equipment.",
    onSiteContact: "On-location coordinator identity.",
    accessHours: "Permitted service window constraints.",
    greaseTrapLocation: "Indoor/outdoor routing and equipment planning.",
    previousServiceHistoryKnown: "Indicates whether history lookup is needed.",
    serviceUrgency: "Commercial-specific urgency mirror used in downstream ops.",
  },
};
